server:
  servlet:
    context-path: /test  # 这将是您的应用上下文路径
    encoding:
      charset: UTF-8
      force: true
spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@//localhost:1521/orcl
    username: C##WEBSTORE
    password: 123456
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.model
  configuration:
    map-underscore-to-camel-case: true